# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{easy-sitemaps}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["varchar", "robustdj"]
  s.date = %q{2010-04-01}
  s.email = %q{charlesmbowman@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "easy-sitemaps.gemspec",
     "gem-private_key.pem",
     "gem-public_cert.pem",
     "init.rb",
     "lib/easy-sitemaps.rb",
     "lib/ip/active_record.rb",
     "lib/ip/processor.rb",
     "lib/ip/urlset.rb",
     "pkg/easy-sitemaps-0.0.1.gem",
     "pkg/easy-sitemaps-0.0.2.gem",
     "pkg/sitemaps-0.0.1.gem",
     "sitemaps-0.0.1.gem",
     "spec/ip/processor_spec.rb",
     "spec/ip/urlset_spec.rb",
     "spec/resources/foo.rb",
     "spec/resources/public/foo_urlset_1.xml",
     "spec/resources/public/foo_urlset_1.xml.gz",
     "spec/resources/public/sitemap_index.xml",
     "spec/resources/sitemap.xml",
     "tasks/rails.rb",
     "tasks/sitemaps.rake"
  ]
  s.homepage = %q{http://github.com/varchar/foo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easy Sitemaps for Rails}
  s.test_files = [
    "spec/ip/processor_spec.rb",
     "spec/ip/urlset_spec.rb",
     "spec/resources/foo.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.0"])
      s.add_development_dependency(%q<roxml>, [">= 3.0"])
      s.add_development_dependency(%q<action_view>, [">= 2.3.2"])
      s.add_development_dependency(%q<action_controller>, [">= 2.3.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.0"])
      s.add_dependency(%q<roxml>, [">= 3.0"])
      s.add_dependency(%q<action_view>, [">= 2.3.2"])
      s.add_dependency(%q<action_controller>, [">= 2.3.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.0"])
    s.add_dependency(%q<roxml>, [">= 3.0"])
    s.add_dependency(%q<action_view>, [">= 2.3.2"])
    s.add_dependency(%q<action_controller>, [">= 2.3.2"])
  end
end

